#!/usr/bin/env python3
"""
Script to update AssetLoader to use new subfolder structure
"""

import re

# Read the current assets.py file
with open('src/core/assets.py', 'r') as f:
    content = f.read()

# Define the mapping of files to their new subfolder paths
asset_mappings = {
    # Characters
    "ancient_dragon.png": "characters/ancient_dragon.png",
    "ancient_guardian.png": "characters/ancient_guardian.png", 
    "ancient_scorpion_king.png": "characters/ancient_scorpion_king.png",
    "assayer.png": "characters/assayer.png",
    "bandit_captain.png": "characters/bandit_captain.png",
    "bandit_raider.png": "characters/bandit_raider.png",
    "bandit_scout.png": "characters/bandit_scout.png",
    "banker.png": "characters/banker.png",
    "barkeeper.png": "characters/barkeeper.png",
    "boat_builder.png": "characters/boat_builder.png",
    "bog_sprite.png": "characters/bog_sprite.png",
    "bog_witch.png": "characters/bog_witch.png",
    "caravan_master.png": "characters/caravan_master.png",
    "craftsman.png": "characters/craftsman.png",
    "crystal_elemental.png": "characters/crystal_elemental.png",
    "dark_mage.png": "characters/dark_mage.png",
    "desert_guide.png": "characters/desert_guide.png",
    "desert_lich.png": "characters/desert_lich.png",
    "desert_nomad.png": "characters/desert_nomad.png",
    "desert_scorpion.png": "characters/desert_scorpion.png",
    "desert_warlord.png": "characters/desert_warlord.png",
    "elder_forest_sprite.png": "characters/elder_forest_sprite.png",
    "elder_npc.png": "characters/elder_npc.png",
    "fire_drake.png": "characters/fire_drake.png",
    "forest_dragon.png": "characters/forest_dragon.png",
    "forest_ranger.png": "characters/forest_ranger.png",
    "forest_sprite.png": "characters/forest_sprite.png",
    "frost_giant.png": "characters/frost_giant.png",
    "frost_mage.png": "characters/frost_mage.png",
    "frost_sprite.png": "characters/frost_sprite.png",
    "fur_trader.png": "characters/fur_trader.png",
    "generic_child.png": "characters/generic_child.png",
    "generic_citizen.png": "characters/generic_citizen.png",
    "generic_elder.png": "characters/generic_elder.png",
    "generic_farmer.png": "characters/generic_farmer.png",
    "generic_merchant_helper.png": "characters/generic_merchant_helper.png",
    "generic_npc.png": "characters/generic_npc.png",
    "generic_servant.png": "characters/generic_servant.png",
    "generic_villager_1.png": "characters/generic_villager_1.png",
    "generic_villager_2.png": "characters/generic_villager_2.png",
    "generic_worker.png": "characters/generic_worker.png",
    "giant_scorpion.png": "characters/giant_scorpion.png",
    "goblin_archer.png": "characters/goblin_archer.png",
    "goblin_chieftain.png": "characters/goblin_chieftain.png",
    "goblin_sprite.png": "characters/goblin_sprite.png",
    "guard_captain.png": "characters/guard_captain.png",
    "guild_master.png": "characters/guild_master.png",
    "harbor_master.png": "characters/harbor_master.png",
    "head_miner.png": "characters/head_miner.png",
    "high_priest.png": "characters/high_priest.png",
    "ice_dragon.png": "characters/ice_dragon.png",
    "ice_keeper.png": "characters/ice_keeper.png",
    "ice_troll.png": "characters/ice_troll.png",
    "ice_wolf.png": "characters/ice_wolf.png",
    "innkeeper.png": "characters/innkeeper.png",
    "librarian.png": "characters/librarian.png",
    "lodge_keeper.png": "characters/lodge_keeper.png",
    "master_fisher.png": "characters/master_fisher.png",
    "master_herbalist.png": "characters/master_herbalist.png",
    "master_smith.png": "characters/master_smith.png",
    "master_woodcutter.png": "characters/master_woodcutter.png",
    "mayor.png": "characters/mayor.png",
    "miller.png": "characters/miller.png",
    "mine_foreman.png": "characters/mine_foreman.png",
    "mushroom_farmer.png": "characters/mushroom_farmer.png",
    "mysterious_wizard.png": "characters/mysterious_wizard.png",
    "noble.png": "characters/noble.png",
    "npc_shopkeeper.png": "characters/npc_shopkeeper.png",
    "old_hermit.png": "characters/old_hermit.png",
    "orc_berserker.png": "characters/orc_berserker.png",
    "orc_boss_sprite.png": "characters/orc_boss_sprite.png",
    "orc_crossbow.png": "characters/orc_crossbow.png",
    "orc_scout.png": "characters/orc_scout.png",
    "orc_warrior.png": "characters/orc_warrior.png",
    "plague_bearer.png": "characters/plague_bearer.png",
    "player_sprite.png": "characters/player_sprite.png",
    "poison_archer.png": "characters/poison_archer.png",
    "sand_elemental.png": "characters/sand_elemental.png",
    "sand_viper.png": "characters/sand_viper.png",
    "skeleton_archer.png": "characters/skeleton_archer.png",
    "stable_master.png": "characters/stable_master.png",
    "swamp_dragon.png": "characters/swamp_dragon.png",
    "swamp_hydra.png": "characters/swamp_hydra.png",
    "swamp_lord.png": "characters/swamp_lord.png",
    "swamp_rat.png": "characters/swamp_rat.png",
    "swamp_troll.png": "characters/swamp_troll.png",
    "swamp_witch.png": "characters/swamp_witch.png",
    "trade_master.png": "characters/trade_master.png",
    "trader.png": "characters/trader.png",
    "village_guard_sprite.png": "characters/village_guard_sprite.png",
    "water_keeper.png": "characters/water_keeper.png",
    "wild_boar.png": "characters/wild_boar.png",
    
    # Items
    "antidote.png": "items/antidote.png",
    "bronze_mace.png": "items/bronze_mace.png",
    "chain_mail.png": "items/chain_mail.png",
    "coin.png": "items/coin.png",
    "crossbow.png": "items/crossbow.png",
    "crystal_gem.png": "items/crystal_gem.png",
    "crystal_staff.png": "items/crystal_staff.png",
    "dragon_scale_armor.png": "items/dragon_scale_armor.png",
    "gold_ring.png": "items/gold_ring.png",
    "health_potion.png": "items/health_potion.png",
    "iron_sword.png": "items/iron_sword.png",
    "leather_armor.png": "items/leather_armor.png",
    "mage_robes.png": "items/mage_robes.png",
    "magic_bow.png": "items/magic_bow.png",
    "magic_scroll.png": "items/magic_scroll.png",
    "mana_potion.png": "items/mana_potion.png",
    "plate_armor.png": "items/plate_armor.png",
    "royal_armor.png": "items/royal_armor.png",
    "scale_mail.png": "items/scale_mail.png",
    "silver_dagger.png": "items/silver_dagger.png",
    "stamina_potion.png": "items/stamina_potion.png",
    "steel_axe.png": "items/steel_axe.png",
    "strength_potion.png": "items/strength_potion.png",
    "studded_leather.png": "items/studded_leather.png",
    "throwing_knife.png": "items/throwing_knife.png",
    "war_hammer.png": "items/war_hammer.png",
    
    # Environment
    "brick_tile.png": "environment/brick_tile.png",
    "cactus_barrel.png": "environment/cactus_barrel.png",
    "cactus_saguaro.png": "environment/cactus_saguaro.png",
    "dead_tree.png": "environment/dead_tree.png",
    "desert_rock.png": "environment/desert_rock.png",
    "dirt_tile.png": "environment/dirt_tile.png",
    "fallen_log.png": "environment/fallen_log.png",
    "forest_floor_tile.png": "environment/forest_floor_tile.png",
    "frozen_rock.png": "environment/frozen_rock.png",
    "grass_tile.png": "environment/grass_tile.png",
    "ice_block.png": "environment/ice_block.png",
    "oak_tree.png": "environment/oak_tree.png",
    "pine_tree.png": "environment/pine_tree.png",
    "rock.png": "environment/rock.png",
    "sand_tile.png": "environment/sand_tile.png",
    "snow_tile.png": "environment/snow_tile.png",
    "snowy_pine.png": "environment/snowy_pine.png",
    "stone_tile.png": "environment/stone_tile.png",
    "swamp_log.png": "environment/swamp_log.png",
    "swamp_mushroom.png": "environment/swamp_mushroom.png",
    "swamp_tile.png": "environment/swamp_tile.png",
    "tree.png": "environment/tree.png",
    "water_tile.png": "environment/water_tile.png",
    
    # Buildings
    "archway_texture_tall.png": "buildings/archway_texture_tall.png",
    "door.png": "buildings/door.png",
    "roof_texture.png": "buildings/roof_texture.png",
    "wall_door.png": "buildings/wall_door.png",
    "wall_texture.png": "buildings/wall_texture.png",
    "wall_texture_window.png": "buildings/wall_texture_window.png",
    "wall_tile.png": "buildings/wall_tile.png",
    
    # Furniture
    "bar.png": "furniture/bar.png",
    "bed.png": "furniture/bed.png",
    "chair.png": "furniture/chair.png",
    "desk.png": "furniture/desk.png",
    "fancy_bed.png": "furniture/fancy_bed.png",
    "kitchen.png": "furniture/kitchen.png",
    "shelf.png": "furniture/shelf.png",
    "storage.png": "furniture/storage.png",
    "table.png": "furniture/table.png",
    "tool_rack.png": "furniture/tool_rack.png",
    "weapon_rack.png": "furniture/weapon_rack.png",
    
    # Chests
    "gold_chest_closed.png": "chests/gold_chest_closed.png",
    "gold_chest_open.png": "chests/gold_chest_open.png",
    "iron_chest_closed.png": "chests/iron_chest_closed.png",
    "iron_chest_open.png": "chests/iron_chest_open.png",
    "magical_chest_closed.png": "chests/magical_chest_closed.png",
    "magical_chest_open.png": "chests/magical_chest_open.png",
    "storage_chest.png": "chests/storage_chest.png",
    "wooden_chest_closed.png": "chests/wooden_chest_closed.png",
    "wooden_chest_open.png": "chests/wooden_chest_open.png",
    
    # UI
    "goose_rpg_icon.png": "ui/goose_rpg_icon.png",
    "goose_rpg_icon_bg.png": "ui/goose_rpg_icon_bg.png",
    "goose_rpg_logo.png": "ui/goose_rpg_logo.png",
    "goose_rpg_square_logo.png": "ui/goose_rpg_square_logo.png",
    "menu_background.png": "ui/menu_background.png"
}

# Update all the file paths in the content
for old_path, new_path in asset_mappings.items():
    # Replace quoted strings like "filename.png" with "subfolder/filename.png"
    content = content.replace(f'"{old_path}"', f'"{new_path}"')

# Write the updated content back
with open('src/core/assets.py', 'w') as f:
    f.write(content)

print("✅ Updated AssetLoader with new subfolder paths!")
print(f"📁 Updated {len(asset_mappings)} asset paths")